---
title: "Functional pathway analysis OA"
author: "Li-Fang Yeo"
date: "25 July 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```
```{r}
library(readr)
library(dplyr)
library(mia)
```
```{r}
pw <- read_delim("data/subset_pathabundance-cpm.tsv", 
     delim = "\t", escape_double = FALSE, 
     trim_ws = TRUE)
```
#Clean up
```{r}
colnames(pw) <- gsub("HFJYKBBXY_", "", colnames(pw))
colnames(pw) <- gsub("HHCNCBBXY_", "", colnames(pw))
colnames(pw) <- gsub("_.*", "", colnames(pw))
pw <- pw %>% rename("Pathway"  = "# Pathway")

#discrepancy between sampleID
pw <- pw %>% rename(TM0123M = TM123M) %>%
             rename(TM0167F = TM167F) %>%
             rename(TM0169M = TM169M)
pw1 <- pw %>% 
  filter(rowSums(across(where(is.numeric)))!=0) %>%
  #grep all Pathways that end with species
  filter(!grepl('.s__', Pathway)) %>%
  #remove all unintegrated pathways
  filter(!grepl('UNINTEGRATED|superpathway', Pathway)) 

pw1
# filtered to only prevalent pathways
pw1 <- pw1 %>% tibble::rownames_to_column("Pathway") 

pw1.t <- as.data.frame(t(pw1))
colnames(pw1.t) <- pw1.t[1,]
#remove extra row
pw1.t <- pw1.t[-1, ] 
#change from character to numeric
pw1.t <- pw1.t %>% mutate_if(is.character, as.numeric) %>%
  tibble::rownames_to_column("Barcode") 
```
```{r, echo=FALSE, message=FALSE}
pw10 <- pw1.t %>% 
  select(-1) %>%
  #mutate to 1 for everything > 0.0000000001
  mutate(across(everything(), ~ . > 1e-10)) %>%
  #get proportion
  summarize(across(everything(), mean)) %>%
  tidyr::gather(Pathway,prevalence) %>%
  #filter for pathways that are prevalent in 5%
  dplyr::filter(prevalence >0.05) 

hi <- pw10 %>% 
  #select(-2) %>%
  dplyr::inner_join(pw1, by="Pathway") %>%
  t() %>%
  as.data.frame()

#take first row as colname
colnames(hi) <- hi[1,]
#remove extra row
hi <- hi[-c(1, 2),] 
#change from character to numeric
hi <- hi %>% mutate_if(is.character, as.numeric) %>%
  tibble::rownames_to_column("Barcode") 
```
Reduce to dichotomous variables (absence / presence)
```{r}
#Get df that has prevalence filtered pathway
#Dichotomise
poo_dicho <- hi %>% 
  mutate(across(where(is.numeric), ~ ifelse(. > 0.000, 1, 0)))
```
join functional data to metadata
```{r}
#Match samples with (filtered) tse
a <- as.data.frame(colData(tse))%>%
  tibble::rownames_to_column("Barcode")
a$Group.Bi <- a$Group.Bi %>% as.numeric()

df <- dplyr::inner_join(poo_dicho, a, by = "Barcode")
```
```{r}
lm_group_partial <- purrr::partial(lm, formula = Group.Bi ~ term) %>%
                    purrr::possibly()


#Take the column names from Pathway in shit dataframe as a list and mutate
try <- pw10 %>% 
  dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_group_partial(data = df %>% dplyr::rename(term=.x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "term") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  #write.csv("Functional-dicho.csv")
  DT::datatable(caption = "Linear model for MetaCyc pathways - rural vs urban")
```
Tranform to inverse_rank
```{r}
# Define the transformation function
transform_column <- function(x) {
  qnorm((rank(x, na.last = "keep") - 0.5) / sum(!is.na(x)))
}

# Apply the transformation to all columns
poo_rank <- hi
poo_rank[, -1] <- lapply(hi[, -1], transform_column)
```
Data wrangling to join functional data to metadata
```{r}
#Here you will have the correct number of samples
df <- dplyr::right_join(poo_rank, a, by = "Barcode")

##Linear model for inverse rank
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- pw10 %>% 
  dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_group_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "term") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  #write.csv("Functional-IRN.csv")
  DT::datatable(caption = "Linear model Inverse Rank Normalised for MetaCyc pathways - Rural urban")
```






